#!/usr/bin/perl -w
use strict;

my @ids = `docker images --no-trunc --format '{{.ID}}'` =~ /(\S+)/g;
my @images = map {
    my ($names, $ids) = /\[(.*?)\] \[(.*?)\]/ or die "weird <$_>";
    map {
        s/:latest$//; # on simplifie le nom
        { name => $_, ids => "$ids " }
    } split(" ", $names)
} `docker inspect --format='{{.RepoTags}} {{.RootFS.Layers}}' @ids | uniq`;

foreach my $image (sort { $a->{name} cmp $b->{name} } @images) {   
    my $name = $image->{name};
    if ($name =~ /^up1-/) {
        my @parents = grep { $image != $_ && starts_with($image->{ids}, $_->{ids}) && $image->{ids} ne $_->{ids} } @images;
        printf "%-30s %s\n", $name, join(' ', map { $_->{name} } @parents);
    }
}

sub starts_with {
    rindex($_[0], $_[1], 0) == 0
}