#!/usr/bin/perl -w
use strict;

my %id2names;
my @names;
foreach (`docker images --no-trunc --format '{{.ID}} {{.Repository}}:{{.Tag}}'`) {
    s/:latest$//; # on simplifie le nom
    my ($id, $name) = split;
    push @{$id2names{$id}}, $name;
    push @names, $name;
}

my @l = `docker history --no-trunc --format '{{.ID}} {{.Size}}' $ARGV[0]`;
my $totalSize = 0;
my $i = 0;
foreach (reverse @l) {
    my ($Id, $Size) = split;
    $Size =~ s/GB$/ * 1024*1024*1024/;
    $Size =~ s/MB$/ * 1024*1024/;
    $Size =~ s/kB$/ * 1024/;
    $Size =~ s/B$//;
    $totalSize += eval $Size;
    my @parents = @{$id2names{$Id} || []};
    if (@parents) {
        printf "%-50s %6sMB\n", join(' ', @parents), ($i++ == 0 ? "" : "+") . int($totalSize / 1024/1024);
        $totalSize = 0;
    }
}
